name: Run Plugin Tests

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        SHOW_ENDPOINT_RETURNS: true
        REDIS_HOST: redis://localhost
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-replica-set: test-rs

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ..
        git clone https://github.com/Jaseci-Labs/jaclang.git
        cd jaclang
        pip install -e .
        cd ../jac-cloud
        pip install pytest
        pip install -e .

    - name: Run tests
      run: |
        jac clean
        jac tool gen_parser
        jac serve jaclang_jaseci/tests/simple_graph.jac --port 8000 &
        sleep 3
        pytest